### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by dai-shi** [dai-shi/apollo-link-lazy#4]
Since upgrading graphql-tools v6, both examples are not working.

It says: `Error: Error: Cannot return null for non-nullable field Query.posts.`

Something must be wrong with makeExecutableSchema or addMocksToSchema.

**Comment by jacobodeharo** [comment]
Hi, I have created a PR that fixes the examples: https://github.com/dai-shi/apollo-link-lazy/pull/5

Regards.
